"""add adp table

Revision ID: 42e19203c52e
Revises: e86061d21045
Create Date: 2026-08-04 10:10:22.826987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e19203c52e'
down_revision: Union[str, Sequence[str], None] = 'e86061d21045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('teams', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('stdev', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['player_ids.canonical_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id', 'source', 'format', 'teams', name='uq_adp_key')
    )
    op.create_index(op.f('ix_adp_canonical_id'), 'adp', ['canonical_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adp_canonical_id'), table_name='adp')
    op.drop_table('adp')
    # ### end Alembic commands ###
