"""add game lines

Revision ID: 71ebea0c1bf4
Revises: 623c80d109ec
Create Date: 2026-08-05 14:04:54.861694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ebea0c1bf4'
down_revision: Union[str, Sequence[str], None] = '623c80d109ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=4), nullable=False),
    sa.Column('away_team', sa.String(length=4), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spread_line', sa.Float(), nullable=True),
    sa.Column('total_line', sa.Float(), nullable=True),
    sa.Column('home_moneyline', sa.Integer(), nullable=True),
    sa.Column('away_moneyline', sa.Integer(), nullable=True),
    sa.Column('roof', sa.String(length=16), nullable=True),
    sa.Column('surface', sa.String(length=24), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('wind', sa.Float(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', name='uq_game_line_key')
    )
    op.create_index(op.f('ix_game_lines_away_team'), 'game_lines', ['away_team'], unique=False)
    op.create_index(op.f('ix_game_lines_game_id'), 'game_lines', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_lines_home_team'), 'game_lines', ['home_team'], unique=False)
    op.create_index(op.f('ix_game_lines_season'), 'game_lines', ['season'], unique=False)
    op.create_index(op.f('ix_game_lines_week'), 'game_lines', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_lines_week'), table_name='game_lines')
    op.drop_index(op.f('ix_game_lines_season'), table_name='game_lines')
    op.drop_index(op.f('ix_game_lines_home_team'), table_name='game_lines')
    op.drop_index(op.f('ix_game_lines_game_id'), table_name='game_lines')
    op.drop_index(op.f('ix_game_lines_away_team'), table_name='game_lines')
    op.drop_table('game_lines')
    # ### end Alembic commands ###
