"""add league registry and rosters

Revision ID: 8b2636e41d7f
Revises: 34ebbbd3c39d
Create Date: 2026-08-05 11:02:42.121107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b2636e41d7f'
down_revision: Union[str, Sequence[str], None] = '34ebbbd3c39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_rosters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('platform_roster_id', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('is_mine', sa.Boolean(), nullable=False),
    sa.Column('player_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unmapped_player_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'platform_roster_id', name='uq_roster_league_slot')
    )
    op.create_index(op.f('ix_league_rosters_league_id'), 'league_rosters', ['league_id'], unique=False)
    op.add_column('leagues', sa.Column('my_team_id', sa.String(length=32), nullable=True))
    op.add_column('leagues', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'active')
    op.drop_column('leagues', 'my_team_id')
    op.drop_index(op.f('ix_league_rosters_league_id'), table_name='league_rosters')
    op.drop_table('league_rosters')
    # ### end Alembic commands ###
