"""add team and opponent to weekly stats

Revision ID: 9d2c7fae70a1
Revises: 71ebea0c1bf4
Create Date: 2026-08-05 14:13:09.793918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2c7fae70a1'
down_revision: Union[str, Sequence[str], None] = '71ebea0c1bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_stats', sa.Column('team', sa.String(length=4), nullable=True))
    op.add_column('weekly_stats', sa.Column('opponent', sa.String(length=4), nullable=True))
    op.create_index(op.f('ix_weekly_stats_team'), 'weekly_stats', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_stats_team'), table_name='weekly_stats')
    op.drop_column('weekly_stats', 'opponent')
    op.drop_column('weekly_stats', 'team')
    # ### end Alembic commands ###
