"""initial schema

Revision ID: e86061d21045
Revises: 
Create Date: 2026-08-04 09:40:02.769262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e86061d21045'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('platform_league_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_league_id', 'season', name='uq_league_platform_id')
    )
    op.create_table('player_ids',
    sa.Column('canonical_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sleeper_id', sa.String(length=16), nullable=True),
    sa.Column('espn_id', sa.String(length=16), nullable=True),
    sa.Column('gsis_id', sa.String(length=16), nullable=True),
    sa.Column('pfr_id', sa.String(length=16), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('merge_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_index(op.f('ix_player_ids_espn_id'), 'player_ids', ['espn_id'], unique=True)
    op.create_index(op.f('ix_player_ids_gsis_id'), 'player_ids', ['gsis_id'], unique=True)
    op.create_index(op.f('ix_player_ids_merge_name'), 'player_ids', ['merge_name'], unique=False)
    op.create_index('ix_player_ids_merge_name_pos', 'player_ids', ['merge_name', 'position'], unique=False)
    op.create_index(op.f('ix_player_ids_pfr_id'), 'player_ids', ['pfr_id'], unique=False)
    op.create_index(op.f('ix_player_ids_position'), 'player_ids', ['position'], unique=False)
    op.create_index(op.f('ix_player_ids_sleeper_id'), 'player_ids', ['sleeper_id'], unique=True)
    op.create_table('league_settings',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('scoring', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roster_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_teams', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('players',
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('injury_status', sa.String(length=32), nullable=True),
    sa.Column('search_rank', sa.Integer(), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['player_ids.canonical_id'], ),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_index(op.f('ix_players_search_rank'), 'players', ['search_rank'], unique=False)
    op.create_index(op.f('ix_players_team'), 'players', ['team'], unique=False)
    op.create_table('projections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['player_ids.canonical_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id', 'source', 'season', 'week', name='uq_projection_key')
    )
    op.create_index(op.f('ix_projections_canonical_id'), 'projections', ['canonical_id'], unique=False)
    op.create_table('weekly_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['player_ids.canonical_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id', 'season', 'week', name='uq_weekly_stat_key')
    )
    op.create_index(op.f('ix_weekly_stats_canonical_id'), 'weekly_stats', ['canonical_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_stats_canonical_id'), table_name='weekly_stats')
    op.drop_table('weekly_stats')
    op.drop_index(op.f('ix_projections_canonical_id'), table_name='projections')
    op.drop_table('projections')
    op.drop_index(op.f('ix_players_team'), table_name='players')
    op.drop_index(op.f('ix_players_search_rank'), table_name='players')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_table('players')
    op.drop_table('league_settings')
    op.drop_index(op.f('ix_player_ids_sleeper_id'), table_name='player_ids')
    op.drop_index(op.f('ix_player_ids_position'), table_name='player_ids')
    op.drop_index(op.f('ix_player_ids_pfr_id'), table_name='player_ids')
    op.drop_index('ix_player_ids_merge_name_pos', table_name='player_ids')
    op.drop_index(op.f('ix_player_ids_merge_name'), table_name='player_ids')
    op.drop_index(op.f('ix_player_ids_gsis_id'), table_name='player_ids')
    op.drop_index(op.f('ix_player_ids_espn_id'), table_name='player_ids')
    op.drop_table('player_ids')
    op.drop_table('leagues')
    # ### end Alembic commands ###
