// Generate extension types from the API's OpenAPI schema (spec 3), so the
// extension cannot silently drift from the models it consumes.
//
//   npm run types        regenerate src/lib/api-types.ts
//   npm run types:check  fail if the checked-in file is stale
//
// The schema is read straight from the FastAPI app object; no server needed.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const OUT = "src/lib/api-types.ts";
const check = process.argv.includes("--check");

const schema = execFileSync(
  "uv",
  ["run", "python", "-c", "import json; from api.main import app; print(json.dumps(app.openapi()))"],
  { cwd: "..", encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
);

const tmp = join(mkdtempSync(join(tmpdir(), "openapi-")), "openapi.json");
writeFileSync(tmp, schema);

const generated = execFileSync(
  "npx",
  ["--yes", "openapi-typescript@7", tmp],
  { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
);

const banner = "// GENERATED by scripts/gen-types.mjs from the API OpenAPI schema. Do not edit.\n";
const next = banner + generated;

if (check) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing counts as stale */
  }
  if (current !== next) {
    console.error(`${OUT} is out of date. Run: npm run types`);
    process.exit(1);
  }
  console.log(`${OUT} is up to date`);
} else {
  writeFileSync(OUT, next);
  console.log(`wrote ${OUT}`);
}
