// GENERATED by scripts/gen-types.mjs from the API OpenAPI schema. Do not edit.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/leagues/{platform}/{league_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** League Settings */
        get: operations["league_settings_leagues__platform___league_id__settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{platform}/{league_id}/draft-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Draft State
         * @description Normalized live draft state with canonical player IDs (Phase 1 acceptance).
         */
        get: operations["draft_state_leagues__platform___league_id__draft_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Leagues
         * @description Leagues this tool manages. In-season jobs iterate exactly this list.
         */
        get: operations["list_leagues_leagues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register League
         * @description Register a league for in-season jobs, then sync it immediately.
         *
         *     Registration is what makes waivers, start/sit and news filtering possible:
         *     those run on a schedule and cannot take a league id from a request.
         */
        post: operations["register_league_leagues_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/espn/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Espn Board
         * @description Ranked board for an ESPN league, from a raw mSettings payload.
         *
         *     The extension fetches the payload with the user's own cookies (the server
         *     holds no ESPN credentials) and re-ranks locally as picks stream in from
         *     the draft room's WebSocket.
         */
        post: operations["espn_board_draft_espn_board_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/espn/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Espn Recommendations
         * @description Recompute ESPN recommendations from live browser-observed draft state.
         */
        post: operations["espn_recommendations_draft_espn_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/{platform}/{draft_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendations
         * @description Best available now, per spec §7.1. Engine knobs overridable as query params.
         */
        get: operations["recommendations_draft__platform___draft_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingest-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ingest Status
         * @description Freshness per job. The draft-day script checks this before you start.
         */
        get: operations["ingest_status_admin_ingest_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingest/{job_name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Ingest */
        post: operations["trigger_ingest_admin_ingest__job_name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List News
         * @description Recent player news, filtered to players who could matter to you.
         *
         *     Relevance is your rostered players plus the top `top_available` by search
         *     rank, per spec 7.4. Items with no identified player are excluded: a feed
         *     padded with league-wide articles is the thing this is meant to avoid.
         */
        get: operations["list_news_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weekly/{league_id}/waivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Waiver Targets
         * @description Best free agents in this league, ranked by what they are worth per game.
         *
         *     Scored on season scoring rate gated by whether the role still exists. Role
         *     change and regression risk ride along as context because both measured worse
         *     than useless as ranking inputs -- see `api.engine.waivers`.
         */
        get: operations["waiver_targets_weekly__league_id__waivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weekly/{league_id}/lineup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommended Lineup
         * @description Best starting lineup from my roster for the week.
         *
         *     Baseline is a published weekly projection where one exists and the player's
         *     own scoring rate otherwise; game environment nudges it. Genuinely close
         *     calls are labelled rather than decided.
         */
        get: operations["recommended_lineup_weekly__league_id__lineup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustmentOut */
        AdjustmentOut: {
            /** Label */
            label: string;
            /** Delta */
            delta: number;
        };
        /** BenchOut */
        BenchOut: {
            /** Canonical Id */
            canonical_id: number;
            /** Name */
            name: string;
            /** Position */
            position: string;
            /** Projected */
            projected: number;
            outlook: components["schemas"]["OutlookOut"] | null;
        };
        /** DraftPick */
        DraftPick: {
            /** Pick No */
            pick_no: number;
            /** Round */
            round: number;
            /** Draft Slot */
            draft_slot: number;
            /** Player Id */
            player_id: string;
            /** Picked By Roster */
            picked_by_roster?: number | null;
        };
        /** DraftState */
        DraftState: {
            /** Drafted Player Ids */
            drafted_player_ids: string[];
            /** My Roster Player Ids */
            my_roster_player_ids: string[];
            /** Current Pick */
            current_pick: number;
            /** My Next Pick */
            my_next_pick: number | null;
            /** Total Teams */
            total_teams: number;
            /** Rounds */
            rounds: number;
            /** Status */
            status: string;
            /** Picks */
            picks: components["schemas"]["DraftPick"][];
        };
        /** EngineParams */
        EngineParams: {
            /**
             * Flex Split
             * @default {
             *       "RB": 0.4,
             *       "WR": 0.55,
             *       "TE": 0.05
             *     }
             */
            flex_split: {
                [key: string]: number;
            };
            /**
             * Superflex Split
             * @default {
             *       "QB": 0.85,
             *       "RB": 0.06,
             *       "WR": 0.08,
             *       "TE": 0.01
             *     }
             */
            superflex_split: {
                [key: string]: number;
            };
            /**
             * Tier Gap Abs
             * @default 6
             */
            tier_gap_abs: number;
            /**
             * Tier Gap Rel
             * @default 2
             */
            tier_gap_rel: number;
            /**
             * Need Boost
             * @default 0.2
             */
            need_boost: number;
            /**
             * Surplus Penalty
             * @default 0.15
             */
            surplus_penalty: number;
            /**
             * Starter Unavailable Rate
             * @default 0.2214
             */
            starter_unavailable_rate: number;
            /**
             * Depth Penalty Floor
             * @default 0.25
             */
            depth_penalty_floor: number;
            /**
             * Run Window
             * @default 8
             */
            run_window: number;
            /**
             * Run Threshold
             * @default 5
             */
            run_threshold: number;
            /**
             * At Risk Threshold
             * @default 0.35
             */
            at_risk_threshold: number;
            /**
             * Simulation Trials
             * @default 64
             */
            simulation_trials: number;
            /**
             * Simulation Seed
             * @default 2026
             */
            simulation_seed: number;
            /**
             * Simulation Run Weight
             * @default 1
             */
            simulation_run_weight: number;
            /**
             * Simulation Candidate Limit
             * @default 12
             */
            simulation_candidate_limit: number;
            /**
             * Simulation Pool Limit
             * @default 120
             */
            simulation_pool_limit: number;
            /**
             * Market Decay Sigma Mult
             * @default 0.4
             */
            market_decay_sigma_mult: number;
            /**
             * Market Decay Min Picks
             * @default 2.5
             */
            market_decay_min_picks: number;
            /**
             * Next Turn Discount
             * @default 0.85
             */
            next_turn_discount: number;
            /**
             * Projection Uncertainty Weight
             * @default 0.15
             */
            projection_uncertainty_weight: number;
            /**
             * Room Urgency Weight
             * @default 0.75
             */
            room_urgency_weight: number;
            /**
             * Te Need Boost After Round
             * @default 6
             */
            te_need_boost_after_round: number;
            /**
             * Qb Need Boost After Round
             * @default 7
             */
            qb_need_boost_after_round: number;
            /**
             * Duplicate Qb Te After Round
             * @default 14
             */
            duplicate_qb_te_after_round: number;
            /**
             * Duplicate Te After Round
             * @default 13
             */
            duplicate_te_after_round: number;
            /**
             * Duplicate Te Exception Margin
             * @default 8
             */
            duplicate_te_exception_margin: number;
            /**
             * Early Duplicate Qb Te Multiplier
             * @default 0.35
             */
            early_duplicate_qb_te_multiplier: number;
            /**
             * Qb Wr Stack Bonus
             * @default 2.5
             */
            qb_wr_stack_bonus: number;
            /**
             * Wr Rb Correlation Penalty
             * @default 2
             */
            wr_rb_correlation_penalty: number;
            /**
             * Reach Grace Picks
             * @default 8
             */
            reach_grace_picks: number;
            /**
             * Reach Penalty Per Pick
             * @default 0.25
             */
            reach_penalty_per_pick: number;
            /**
             * Max Reach Penalty
             * @default 5
             */
            max_reach_penalty: number;
            /**
             * Hidden Gem Market Window
             * @default 18
             */
            hidden_gem_market_window: number;
            /**
             * Hidden Gem Min Value
             * @default 3
             */
            hidden_gem_min_value: number;
            /**
             * Hidden Gem Count
             * @default 1
             */
            hidden_gem_count: number;
            /**
             * Positions
             * @default [
             *       "QB",
             *       "RB",
             *       "WR",
             *       "TE",
             *       "K",
             *       "DEF"
             *     ]
             */
            positions: string[];
            /**
             * Position Discount
             * @default {
             *       "K": 0.5,
             *       "DEF": 0.5
             *     }
             */
            position_discount: {
                [key: string]: number;
            };
            /**
             * Late Fill Positions
             * @default [
             *       "K",
             *       "DEF"
             *     ]
             */
            late_fill_positions: string[];
            /**
             * Late Fill Buffer
             * @default 2
             */
            late_fill_buffer: number;
        };
        /** EspnLiveDraftRequest */
        EspnLiveDraftRequest: {
            /** League Json */
            league_json: {
                [key: string]: unknown;
            };
            /** Picked Player Ids */
            picked_player_ids: string[];
            /** Picked Team Ids */
            picked_team_ids?: number[] | null;
            /** Schedule */
            schedule: {
                [key: string]: number;
            };
            /** My Team Id */
            my_team_id?: number | null;
            /** My Pick Numbers */
            my_pick_numbers?: number[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HiddenGem */
        HiddenGem: {
            player: components["schemas"]["RankedPlayer"];
            /** Target Pick Min */
            target_pick_min: number;
            /** Target Pick Max */
            target_pick_max: number;
            /** Upside */
            upside: string;
            /** Risk */
            risk: string;
        };
        /** IngestStatus */
        IngestStatus: {
            /** Jobs */
            jobs: components["schemas"]["JobStatus"][];
            /** Any Due */
            any_due: boolean;
        };
        /** JobStatus */
        JobStatus: {
            /** Job */
            job: string;
            /** Description */
            description: string;
            /** Interval Hours */
            interval_hours: number;
            /** Last Success */
            last_success: string | null;
            /** Age Hours */
            age_hours: number | null;
            /** Due */
            due: boolean;
        };
        /** LeagueSettings */
        LeagueSettings: {
            /** Scoring */
            scoring: {
                [key: string]: number;
            };
            /** Roster Slots */
            roster_slots: {
                [key: string]: number;
            };
            /**
             * Position Limits
             * @default {}
             */
            position_limits: {
                [key: string]: number;
            };
            /** Total Teams */
            total_teams: number;
        };
        /** LineupResponse */
        LineupResponse: {
            /** League Id */
            league_id: number;
            /** Season */
            season: string;
            /** Week */
            week: number;
            /** Projected Total */
            projected_total: number;
            /** Starters */
            starters: components["schemas"]["StarterOut"][];
            /** Bench */
            bench: components["schemas"]["BenchOut"][];
            /** Unfilled */
            unfilled: string[];
            /** Unsupported */
            unsupported: string[];
            /** Toss Ups */
            toss_ups: number;
        };
        /** NewsEntry */
        NewsEntry: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
            /** Published At */
            published_at: string | null;
            /** Tag */
            tag: string;
            /** Player */
            player: string | null;
            /** Position */
            position: string | null;
            /** Team */
            team: string | null;
            /** On My Roster */
            on_my_roster: boolean;
        };
        /** NextTurnSimulation */
        NextTurnSimulation: {
            /** Trials */
            trials: number;
            /** Seed */
            seed: number;
            /** Picks Simulated */
            picks_simulated: number;
            /** Disappearance Probability */
            disappearance_probability: {
                [key: string]: number;
            };
            /** Expected Fallback Value */
            expected_fallback_value: {
                [key: string]: number;
            };
            /** Expected Fallback Player */
            expected_fallback_player: {
                [key: string]: string | null;
            };
        };
        /**
         * OfflineKnobs
         * @description Engine knobs the offline fallback has to mirror to stay consistent.
         *
         *     The extension re-ranks a cached board when the API is unreachable, which
         *     means it reimplements a slice of the engine's roster rules. Hardcoding these
         *     on that side made an `EngineParams` change silently desync offline advice
         *     from live advice with nothing to catch it, so the values ride along with the
         *     board that was built from them.
         */
        OfflineKnobs: {
            /** Duplicate Qb Te After Round */
            duplicate_qb_te_after_round: number;
            /** Duplicate Te After Round */
            duplicate_te_after_round: number;
            /** Early Duplicate Qb Te Multiplier */
            early_duplicate_qb_te_multiplier: number;
            /** Qb Wr Stack Bonus */
            qb_wr_stack_bonus: number;
            /** Wr Rb Correlation Penalty */
            wr_rb_correlation_penalty: number;
            /** Startable Slots */
            startable_slots: {
                [key: string]: number;
            };
            /** Starter Unavailable Rate */
            starter_unavailable_rate: number;
            /** Depth Penalty Floor */
            depth_penalty_floor: number;
        };
        /**
         * OutlookOut
         * @description Two 0-100 meters plus the real quantities they are drawn from.
         */
        OutlookOut: {
            /** Risk */
            risk: number;
            /** Reward */
            reward: number;
            /** Bust Probability */
            bust_probability: number;
            /** Projected Ceiling */
            projected_ceiling: number;
            /** Label */
            label: string;
            /** Drivers */
            drivers: string[];
        };
        /**
         * PlayerAnalysis
         * @description Expandable, source-honest context for a recommendation.
         */
        PlayerAnalysis: {
            /** Headline */
            headline: string;
            /** Projection Summary */
            projection_summary: string;
            /** Projection Consensus */
            projection_consensus: number;
            /** Projection Low */
            projection_low: number;
            /** Projection High */
            projection_high: number;
            /** Projection Is Placeholder */
            projection_is_placeholder: boolean;
            /** Roster Fit */
            roster_fit: string;
            /** Timing */
            timing: string;
            /** Model Factors */
            model_factors: string[];
            /** Usage */
            usage: string[];
            /** Team Context */
            team_context: string[];
            /** Advanced */
            advanced: string[];
            /** Advanced Summary */
            advanced_summary: string | null;
            /** Status */
            status: string | null;
            /** Risks */
            risks: string[];
            /** Data Freshness */
            data_freshness: string | null;
        };
        /** RankedPlayer */
        RankedPlayer: {
            /** Canonical Id */
            canonical_id: string;
            /** Name */
            name: string;
            /** Position */
            position: string;
            /** Team */
            team: string | null;
            /** Points */
            points: number;
            /** Vor */
            vor: number;
            /** Value */
            value: number;
            /** Score */
            score: number;
            /** Tier */
            tier: number;
            /** Tier Remaining */
            tier_remaining: number;
            /** Adp */
            adp: number | null;
            /** Survival */
            survival: number;
            /** Disappearance Probability */
            disappearance_probability: number;
            /** At Risk */
            at_risk: boolean;
            /** Opportunity Cost */
            opportunity_cost: number;
            /** Expected Next Turn Value */
            expected_next_turn_value: number;
            /** Reach Penalty */
            reach_penalty: number;
            /** Reason */
            reason: string;
            /** Platform Ids */
            platform_ids: {
                [key: string]: string;
            };
            analysis: components["schemas"]["PlayerAnalysis"];
            /**
             * Held For Later
             * @default false
             */
            held_for_later: boolean;
            /**
             * Pos Rank
             * @default 0
             */
            pos_rank: number;
        };
        /** Recommendation */
        Recommendation: {
            recommended_pick: components["schemas"]["RankedPlayer"];
            room_pick: components["schemas"]["RankedPlayer"];
            /** Picks Agree */
            picks_agree: boolean;
            /** Alternates */
            alternates: components["schemas"]["RankedPlayer"][];
            /** Board */
            board: components["schemas"]["RankedPlayer"][];
            /** Hidden Gems */
            hidden_gems: components["schemas"]["HiddenGem"][];
            simulation: components["schemas"]["NextTurnSimulation"];
            /** Tier Gone Risk */
            tier_gone_risk: number;
            run_alert: components["schemas"]["RunAlert"] | null;
            /** Picks Until Next */
            picks_until_next: number | null;
            /** On Clock */
            on_clock: boolean;
            offline_knobs: components["schemas"]["OfflineKnobs"];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** RegisterLeague */
        RegisterLeague: {
            /** Platform */
            platform: string;
            /** League Id */
            league_id: string;
            /**
             * Season
             * @default 2026
             */
            season: string;
            /** My Team Id */
            my_team_id?: string | null;
            /** Name */
            name?: string | null;
        };
        /** RegisteredLeague */
        RegisteredLeague: {
            /** Id */
            id: number;
            /** Platform */
            platform: string;
            /** League Id */
            league_id: string;
            /** Season */
            season: string;
            /** Name */
            name: string | null;
            /** My Team Id */
            my_team_id: string | null;
            /** Active */
            active: boolean;
            /** Rostered Players */
            rostered_players: number;
            /** Unmapped Players */
            unmapped_players: number;
            /** Sync Error */
            sync_error?: string | null;
        };
        /** RunAlert */
        RunAlert: {
            /** Position */
            position: string;
            /** Count */
            count: number;
            /** Window */
            window: number;
        };
        /** StarterOut */
        StarterOut: {
            /** Slot */
            slot: string;
            /** Canonical Id */
            canonical_id: number;
            /** Name */
            name: string;
            /** Position */
            position: string;
            /** Projected */
            projected: number;
            /** Adjustments */
            adjustments: components["schemas"]["AdjustmentOut"][];
            /** Alternative */
            alternative: string | null;
            /** Margin */
            margin: number | null;
            /** Is Toss Up */
            is_toss_up: boolean;
            outlook: components["schemas"]["OutlookOut"] | null;
            /** Reasons */
            reasons: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WaiverResponse */
        WaiverResponse: {
            /** League Id */
            league_id: number;
            /** Season */
            season: string;
            /** Week */
            week: number;
            /** Candidates Considered */
            candidates_considered: number;
            /** Targets */
            targets: components["schemas"]["WaiverTargetOut"][];
        };
        /** WaiverTargetOut */
        WaiverTargetOut: {
            /** Canonical Id */
            canonical_id: number;
            /** Name */
            name: string;
            /** Position */
            position: string;
            /** Team */
            team: string | null;
            /** Score */
            score: number;
            /** Season Ppg */
            season_ppg: number | null;
            /** Recent Ppg */
            recent_ppg: number | null;
            /** Expected Points Recent */
            expected_points_recent: number | null;
            /** Points Over Expected */
            points_over_expected: number | null;
            /** Is Emerging */
            is_emerging: boolean;
            /** Role Intact */
            role_intact: boolean;
            outlook: components["schemas"]["OutlookOut"] | null;
            /** Reasons */
            reasons: string[];
            /** Context */
            context: string[];
            /** Advanced */
            advanced: string[];
            /** Advanced Summary */
            advanced_summary: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    league_settings_leagues__platform___league_id__settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                league_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_state_leagues__platform___league_id__draft_state_get: {
        parameters: {
            query?: {
                my_slot?: number | null;
            };
            header?: never;
            path: {
                platform: string;
                league_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leagues_leagues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredLeague"][];
                };
            };
        };
    };
    register_league_leagues_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterLeague"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredLeague"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    espn_board_draft_espn_board_post: {
        parameters: {
            query?: {
                flex_split?: {
                    [key: string]: number;
                };
                superflex_split?: {
                    [key: string]: number;
                };
                tier_gap_abs?: number;
                tier_gap_rel?: number;
                need_boost?: number;
                surplus_penalty?: number;
                starter_unavailable_rate?: number;
                depth_penalty_floor?: number;
                run_window?: number;
                run_threshold?: number;
                at_risk_threshold?: number;
                simulation_trials?: number;
                simulation_seed?: number;
                simulation_run_weight?: number;
                simulation_candidate_limit?: number;
                simulation_pool_limit?: number;
                market_decay_sigma_mult?: number;
                market_decay_min_picks?: number;
                next_turn_discount?: number;
                projection_uncertainty_weight?: number;
                room_urgency_weight?: number;
                te_need_boost_after_round?: number;
                qb_need_boost_after_round?: number;
                duplicate_qb_te_after_round?: number;
                duplicate_te_after_round?: number;
                duplicate_te_exception_margin?: number;
                early_duplicate_qb_te_multiplier?: number;
                qb_wr_stack_bonus?: number;
                wr_rb_correlation_penalty?: number;
                reach_grace_picks?: number;
                reach_penalty_per_pick?: number;
                max_reach_penalty?: number;
                hidden_gem_market_window?: number;
                hidden_gem_min_value?: number;
                hidden_gem_count?: number;
                positions?: string[];
                position_discount?: {
                    [key: string]: number;
                };
                late_fill_positions?: string[];
                late_fill_buffer?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    espn_recommendations_draft_espn_recommendations_post: {
        parameters: {
            query?: {
                flex_split?: {
                    [key: string]: number;
                };
                superflex_split?: {
                    [key: string]: number;
                };
                tier_gap_abs?: number;
                tier_gap_rel?: number;
                need_boost?: number;
                surplus_penalty?: number;
                starter_unavailable_rate?: number;
                depth_penalty_floor?: number;
                run_window?: number;
                run_threshold?: number;
                at_risk_threshold?: number;
                simulation_trials?: number;
                simulation_seed?: number;
                simulation_run_weight?: number;
                simulation_candidate_limit?: number;
                simulation_pool_limit?: number;
                market_decay_sigma_mult?: number;
                market_decay_min_picks?: number;
                next_turn_discount?: number;
                projection_uncertainty_weight?: number;
                room_urgency_weight?: number;
                te_need_boost_after_round?: number;
                qb_need_boost_after_round?: number;
                duplicate_qb_te_after_round?: number;
                duplicate_te_after_round?: number;
                duplicate_te_exception_margin?: number;
                early_duplicate_qb_te_multiplier?: number;
                qb_wr_stack_bonus?: number;
                wr_rb_correlation_penalty?: number;
                reach_grace_picks?: number;
                reach_penalty_per_pick?: number;
                max_reach_penalty?: number;
                hidden_gem_market_window?: number;
                hidden_gem_min_value?: number;
                hidden_gem_count?: number;
                positions?: string[];
                position_discount?: {
                    [key: string]: number;
                };
                late_fill_positions?: string[];
                late_fill_buffer?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EspnLiveDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_draft__platform___draft_id__recommendations_get: {
        parameters: {
            query?: {
                params?: components["schemas"]["EngineParams"];
                my_slot?: number | null;
            };
            header?: never;
            path: {
                platform: string;
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_status_admin_ingest_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestStatus"];
                };
            };
        };
    };
    trigger_ingest_admin_ingest__job_name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_news_news_get: {
        parameters: {
            query?: {
                league_id?: number | null;
                hours?: number;
                limit?: number;
                mine_only?: boolean;
                top_available?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    waiver_targets_weekly__league_id__waivers_get: {
        parameters: {
            query?: {
                week?: number | null;
                limit?: number;
                /** @description Override the league's season; useful for reviewing a past year. */
                season?: string | null;
            };
            header?: never;
            path: {
                league_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaiverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommended_lineup_weekly__league_id__lineup_get: {
        parameters: {
            query?: {
                week?: number | null;
                /** @description Override the league's season; useful for reviewing a past year. */
                season?: string | null;
            };
            header?: never;
            path: {
                league_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
